name: build-all
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # install actions
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.23.2'

      # build
      - name: build app
        run: go build -o aoc .

      # validate
      - name: run unit tests
        run: go test -short -parallel 8 ./...
      - name: run linter
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.62

      # run
      - name: run all solutions
        run: time ./aoc all
